name: ts

on:
  push:
    paths:
      - 'ts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:10.11.0
    timeout-minutes: 5
    env:
      ELECTRON_EXTRA_LAUNCH_ARGS: '--disable-gpu'
    steps:
    - name: Use Node.js 14.21.2
      uses: actions/setup-node@v1
      with:
        node-version: 14.21.2

    - uses: actions/checkout@v2

    - name: npm install
      run: |
        cd ts
        npm install

    - name: Start Angular server
      run: |
        cd ts
        ng serve --host 0.0.0.0 --disable-host-check --port 4200 &

    - name: Wait for server to start
      run: |
        timeout 60s sh -c 'until nc -z localhost 4200; do sleep 1; done'

    - name: Run tests
      run: |
        cd ts
        npm run cypress:run-base

    - name: Stores screenshots
      uses: actions/upload-artifact@v3
      with:
        name: cypress-screenshots
        path: ./ts/cypress/screenshots
      if: always()

    - name: Stores snapshots
      uses: actions/upload-artifact@v3
      with:
        name: cypress-snapshots
        path: ./ts/cypress/snapshots
      if: always()
